# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_function_song.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/iconfinder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_add_next = QtWidgets.QPushButton(Dialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/plus-green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_add_next.setIcon(icon1)
        self.pushButton_add_next.setObjectName("pushButton_add_next")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.pushButton_add_next)
        self.verticalLayout.addWidget(self.pushButton_add_next)
        self.pushButton_add_end = QtWidgets.QPushButton(Dialog)
        self.pushButton_add_end.setIcon(icon1)
        self.pushButton_add_end.setObjectName("pushButton_add_end")
        self.buttonGroup.addButton(self.pushButton_add_end)
        self.verticalLayout.addWidget(self.pushButton_add_end)
        self.pushButton_add_playlist = QtWidgets.QPushButton(Dialog)
        self.pushButton_add_playlist.setIcon(icon1)
        self.pushButton_add_playlist.setObjectName("pushButton_add_playlist")
        self.buttonGroup.addButton(self.pushButton_add_playlist)
        self.verticalLayout.addWidget(self.pushButton_add_playlist)
        self.pushButton_delete = QtWidgets.QPushButton(Dialog)
        self.pushButton_delete.setStyleSheet("color: rgb(255, 0, 0);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/seo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon2)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.buttonGroup.addButton(self.pushButton_delete)
        self.verticalLayout.addWidget(self.pushButton_delete)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Функции"))
        self.pushButton_add_next.setText(_translate("Dialog", "Воспроизводить далее"))
        self.pushButton_add_end.setText(_translate("Dialog", "Добавить в конец очереди"))
        self.pushButton_add_playlist.setText(_translate("Dialog", "Добавить в плейлист..."))
        self.pushButton_delete.setText(_translate("Dialog", "Удалить из Медиатеки"))
